---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-app-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo-app-dev
  chart:
    git: git@github.com:natalicot/echo_app_helm_chart.git
    path: charts/echo
    ref: dev
  values:
    image:
      repository: natalicot/echo-app
      tag: dev-57cc7403ba46e9a8e288885b5a8482153f26a5d0
    replicaCount: 1
    hpa:
      enabled: false
