---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-app-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: echo-app-prod
  chart:
    git: git@github.com:natalicot/echo_app_helm_chart
    path: charts/echo
    ref: master
  values:
    image:
      repository: natalicot/echo-app
      tag: 1.0.18
    replicaCount: 1
