---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-app-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: echo-app-prod
  chart:
    git: git@github.com:natalicot/echo_app_helm_chart
    path: charts/echo
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 0.4.11
    replicaCount: 3
