---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-app-stg
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echo-app-stg
  chart:
    git: git@github.com:natalicot/echo_app_helm_chart
    path: echo_app_helm_chart/echo
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: stg-9ij63o4c
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
